defaults: &defaults
  adapter: mysql2
  pool: 5
  encoding: utf8
  timeout: 5000
  username: root
  password: ''

development:
  <<: *defaults
  database: splashpage_development

production:
  <<: *defaults
  database: splashpage_production
